name: Build CPython Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build CPython
      run: |
        cd PCbuild
        ./build.bat -e -d
      shell: cmd

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-windows-build
        path: |
          PCbuild/amd64/*.exe
          PCbuild/amd64/*.dll
          PCbuild/amd64/*.pyd
