name: Build IRRpython Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build CPython
      run: |
        cd PCbuild
        ./build.bat -e -r
      shell: cmd

    - name: Package IRRpython
      run: |
        mkdir IRRpython-dist
        copy PCbuild\amd64\python.exe IRRpython-dist\
        copy PCbuild\amd64\*.dll IRRpython-dist\
        copy PCbuild\amd64\*.pyd IRRpython-dist\
        xcopy /E /I Lib IRRpython-dist\Lib
      shell: cmd

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: IRRpython-windows
        path: IRRpython-dist/
