name: Build IRRpython Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build CPython
      run: |
        cd PCbuild
        ./build.bat -e -r
      shell: cmd

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: IRRpython-windows
        path: |
          PCbuild/amd64/python.exe
          PCbuild/amd64/python3*.dll
          PCbuild/amd64/vcruntime*.dll
          PCbuild/amd64/*.pyd
